version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    image: kellia1903/foodgram_backend:v.1.0
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  frontend:
    image: kellia1903/foodgram_fronted:v.1.0
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    # extra_hosts: #
    #   - "host.docker.internal:host-gateway" #
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
